In [1]:
import pandas as pd
import numpy as np

print("Libraries loaded successfully.")
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Libraries loaded successfully.
Pandas version: 3.0.5
NumPy version: 2.5.2

In [1]:
from pathlib import Path
import pandas as pd

csv_path = Path("../../data/dataset_full.csv")

print("Dataset path:", csv_path.resolve())
print("File exists:", csv_path.exists())

if csv_path.exists():
    df = pd.read_csv(csv_path, nrows=5)
    print("Loaded successfully")
    print("Columns:", len(df.columns))
    print("Column names:")
    print(df.columns.tolist())
    display(df.head(3))

Dataset path: C:\Users\asand\OneDrive\Documents\GitHub\machine-learning-phishing-url-detection\data\dataset_full.csv
File exists: True
Loaded successfully
Columns: 112
Column names:
['qty_dot_url', 'qty_hyphen_url', 'qty_underline_url', 'qty_slash_url', 'qty_questionmark_url', 'qty_equal_url', 'qty_at_url', 'qty_and_url', 'qty_exclamation_url', 'qty_space_url', 'qty_tilde_url', 'qty_comma_url', 'qty_plus_url', 'qty_asterisk_url', 'qty_hashtag_url', 'qty_dollar_url', 'qty_percent_url', 'qty_tld_url', 'length_url', 'qty_dot_domain', 'qty_hyphen_domain', 'qty_underline_domain', 'qty_slash_domain', 'qty_questionmark_domain', 'qty_equal_domain', 'qty_at_domain', 'qty_and_domain', 'qty_exclamation_domain', 'qty_space_domain', 'qty_tilde_domain', 'qty_comma_domain', 'qty_plus_domain', 'qty_asterisk_domain', 'qty_hashtag_domain', 'qty_dollar_domain', 'qty_percent_domain', 'qty_vowels_domain', 'domain_length', 'domain_in_ip', 'server_client_domain', 'qty_dot_directory', 'qty_hyphen_directory', 'qty_underline_directory', 'qty_slash_directory', 'qty_questionmark_directory', 'qty_equal_directory', 'qty_at_directory', 'qty_and_directory', 'qty_exclamation_directory', 'qty_space_directory', 'qty_tilde_directory', 'qty_comma_directory', 'qty_plus_directory', 'qty_asterisk_directory', 'qty_hashtag_directory', 'qty_dollar_directory', 'qty_percent_directory', 'directory_length', 'qty_dot_file', 'qty_hyphen_file', 'qty_underline_file', 'qty_slash_file', 'qty_questionmark_file', 'qty_equal_file', 'qty_at_file', 'qty_and_file', 'qty_exclamation_file', 'qty_space_file', 'qty_tilde_file', 'qty_comma_file', 'qty_plus_file', 'qty_asterisk_file', 'qty_hashtag_file', 'qty_dollar_file', 'qty_percent_file', 'file_length', 'qty_dot_params', 'qty_hyphen_params', 'qty_underline_params', 'qty_slash_params', 'qty_questionmark_params', 'qty_equal_params', 'qty_at_params', 'qty_and_params', 'qty_exclamation_params', 'qty_space_params', 'qty_tilde_params', 'qty_comma_params', 'qty_plus_params', 'qty_asterisk_params', 'qty_hashtag_params', 'qty_dollar_params', 'qty_percent_params', 'params_length', 'tld_present_params', 'qty_params', 'email_in_url', 'time_response', 'domain_spf', 'asn_ip', 'time_domain_activation', 'time_domain_expiration', 'qty_ip_resolved', 'qty_nameservers', 'qty_mx_servers', 'ttl_hostname', 'tls_ssl_certificate', 'qty_redirects', 'url_google_index', 'domain_google_index', 'url_shortened', 'phishing']

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,3,0,0,1,0,0,0,0,0,0,...,1,2,0,892,0,0,0,0,0,1
1,5,0,1,3,0,3,0,2,0,0,...,1,2,1,9540,1,0,0,0,0,1
2,2,0,0,1,0,0,0,0,0,0,...,1,2,3,589,1,0,0,0,0,0

In [7]:
import pandas as pd
from pathlib import Path

file_path = Path(
    r"C:\Users\asand\OneDrive\Documents\GitHub\machine-learning-phishing-url-detection\data\dataset_full.csv"
)

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Dataset shape: (88647, 112)

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,3,0,0,1,0,0,0,0,0,0,...,1,2,0,892,0,0,0,0,0,1
1,5,0,1,3,0,3,0,2,0,0,...,1,2,1,9540,1,0,0,0,0,1
2,2,0,0,1,0,0,0,0,0,0,...,1,2,3,589,1,0,0,0,0,0
3,4,0,2,5,0,0,0,0,0,0,...,1,2,0,292,1,0,0,0,0,1
4,2,0,0,0,0,0,0,0,0,0,...,1,2,1,3597,0,1,0,0,0,0

In [8]:
print("Column names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

print("\nMissing values per column:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Column names:
['qty_dot_url', 'qty_hyphen_url', 'qty_underline_url', 'qty_slash_url', 'qty_questionmark_url', 'qty_equal_url', 'qty_at_url', 'qty_and_url', 'qty_exclamation_url', 'qty_space_url', 'qty_tilde_url', 'qty_comma_url', 'qty_plus_url', 'qty_asterisk_url', 'qty_hashtag_url', 'qty_dollar_url', 'qty_percent_url', 'qty_tld_url', 'length_url', 'qty_dot_domain', 'qty_hyphen_domain', 'qty_underline_domain', 'qty_slash_domain', 'qty_questionmark_domain', 'qty_equal_domain', 'qty_at_domain', 'qty_and_domain', 'qty_exclamation_domain', 'qty_space_domain', 'qty_tilde_domain', 'qty_comma_domain', 'qty_plus_domain', 'qty_asterisk_domain', 'qty_hashtag_domain', 'qty_dollar_domain', 'qty_percent_domain', 'qty_vowels_domain', 'domain_length', 'domain_in_ip', 'server_client_domain', 'qty_dot_directory', 'qty_hyphen_directory', 'qty_underline_directory', 'qty_slash_directory', 'qty_questionmark_directory', 'qty_equal_directory', 'qty_at_directory', 'qty_and_directory', 'qty_exclamation_directory', 'qty_space_directory', 'qty_tilde_directory', 'qty_comma_directory', 'qty_plus_directory', 'qty_asterisk_directory', 'qty_hashtag_directory', 'qty_dollar_directory', 'qty_percent_directory', 'directory_length', 'qty_dot_file', 'qty_hyphen_file', 'qty_underline_file', 'qty_slash_file', 'qty_questionmark_file', 'qty_equal_file', 'qty_at_file', 'qty_and_file', 'qty_exclamation_file', 'qty_space_file', 'qty_tilde_file', 'qty_comma_file', 'qty_plus_file', 'qty_asterisk_file', 'qty_hashtag_file', 'qty_dollar_file', 'qty_percent_file', 'file_length', 'qty_dot_params', 'qty_hyphen_params', 'qty_underline_params', 'qty_slash_params', 'qty_questionmark_params', 'qty_equal_params', 'qty_at_params', 'qty_and_params', 'qty_exclamation_params', 'qty_space_params', 'qty_tilde_params', 'qty_comma_params', 'qty_plus_params', 'qty_asterisk_params', 'qty_hashtag_params', 'qty_dollar_params', 'qty_percent_params', 'params_length', 'tld_present_params', 'qty_params', 'email_in_url', 'time_response', 'domain_spf', 'asn_ip', 'time_domain_activation', 'time_domain_expiration', 'qty_ip_resolved', 'qty_nameservers', 'qty_mx_servers', 'ttl_hostname', 'tls_ssl_certificate', 'qty_redirects', 'url_google_index', 'domain_google_index', 'url_shortened', 'phishing']

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 88647 entries, 0 to 88646
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 75.7 MB

Missing values per column:
qty_dot_url             0
qty_hyphen_url          0
qty_underline_url       0
qty_slash_url           0
qty_questionmark_url    0
                       ..
qty_redirects           0
url_google_index        0
domain_google_index     0
url_shortened           0
phishing                0
Length: 112, dtype: int64

Duplicate rows: 1438

In [9]:
# 1. Display all column names
print("COLUMN NAMES")
print(df.columns.tolist())

# 2. Check data types and missing values
print("\nDATASET INFORMATION")
df.info()

print("\nMISSING VALUES")
print(df.isnull().sum().sort_values(ascending=False).head(20))

# 3. Check duplicate rows
print("\nDUPLICATE ROWS:", df.duplicated().sum())

# 4. Display the last five rows
print("\nLAST FIVE ROWS")
display(df.tail())

COLUMN NAMES
['qty_dot_url', 'qty_hyphen_url', 'qty_underline_url', 'qty_slash_url', 'qty_questionmark_url', 'qty_equal_url', 'qty_at_url', 'qty_and_url', 'qty_exclamation_url', 'qty_space_url', 'qty_tilde_url', 'qty_comma_url', 'qty_plus_url', 'qty_asterisk_url', 'qty_hashtag_url', 'qty_dollar_url', 'qty_percent_url', 'qty_tld_url', 'length_url', 'qty_dot_domain', 'qty_hyphen_domain', 'qty_underline_domain', 'qty_slash_domain', 'qty_questionmark_domain', 'qty_equal_domain', 'qty_at_domain', 'qty_and_domain', 'qty_exclamation_domain', 'qty_space_domain', 'qty_tilde_domain', 'qty_comma_domain', 'qty_plus_domain', 'qty_asterisk_domain', 'qty_hashtag_domain', 'qty_dollar_domain', 'qty_percent_domain', 'qty_vowels_domain', 'domain_length', 'domain_in_ip', 'server_client_domain', 'qty_dot_directory', 'qty_hyphen_directory', 'qty_underline_directory', 'qty_slash_directory', 'qty_questionmark_directory', 'qty_equal_directory', 'qty_at_directory', 'qty_and_directory', 'qty_exclamation_directory', 'qty_space_directory', 'qty_tilde_directory', 'qty_comma_directory', 'qty_plus_directory', 'qty_asterisk_directory', 'qty_hashtag_directory', 'qty_dollar_directory', 'qty_percent_directory', 'directory_length', 'qty_dot_file', 'qty_hyphen_file', 'qty_underline_file', 'qty_slash_file', 'qty_questionmark_file', 'qty_equal_file', 'qty_at_file', 'qty_and_file', 'qty_exclamation_file', 'qty_space_file', 'qty_tilde_file', 'qty_comma_file', 'qty_plus_file', 'qty_asterisk_file', 'qty_hashtag_file', 'qty_dollar_file', 'qty_percent_file', 'file_length', 'qty_dot_params', 'qty_hyphen_params', 'qty_underline_params', 'qty_slash_params', 'qty_questionmark_params', 'qty_equal_params', 'qty_at_params', 'qty_and_params', 'qty_exclamation_params', 'qty_space_params', 'qty_tilde_params', 'qty_comma_params', 'qty_plus_params', 'qty_asterisk_params', 'qty_hashtag_params', 'qty_dollar_params', 'qty_percent_params', 'params_length', 'tld_present_params', 'qty_params', 'email_in_url', 'time_response', 'domain_spf', 'asn_ip', 'time_domain_activation', 'time_domain_expiration', 'qty_ip_resolved', 'qty_nameservers', 'qty_mx_servers', 'ttl_hostname', 'tls_ssl_certificate', 'qty_redirects', 'url_google_index', 'domain_google_index', 'url_shortened', 'phishing']

DATASET INFORMATION
<class 'pandas.DataFrame'>
RangeIndex: 88647 entries, 0 to 88646
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 75.7 MB

MISSING VALUES
qty_dot_url             0
qty_hyphen_url          0
qty_underline_url       0
qty_slash_url           0
qty_questionmark_url    0
qty_equal_url           0
qty_at_url              0
qty_and_url             0
qty_exclamation_url     0
qty_space_url           0
qty_tilde_url           0
qty_comma_url           0
qty_plus_url            0
qty_asterisk_url        0
qty_hashtag_url         0
qty_dollar_url          0
qty_percent_url         0
qty_tld_url             0
length_url              0
qty_dot_domain          0
dtype: int64

DUPLICATE ROWS: 1438

LAST FIVE ROWS

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
88642,3,1,0,0,0,0,0,0,0,0,...,1,3,1,3597,0,0,0,0,0,0
88643,2,0,0,0,0,0,0,0,0,0,...,1,2,2,591,0,2,0,0,0,0
88644,2,1,0,5,0,0,0,0,0,0,...,1,2,5,14391,1,0,0,0,0,1
88645,2,0,0,1,0,0,0,0,0,0,...,1,1,1,52,1,0,0,0,0,1
88646,2,0,0,0,0,0,0,0,0,0,...,1,4,0,299,0,0,0,0,0,0

In [10]:
print("All dataset columns:")

for i, column in enumerate(df.columns):
    print(i, column)

All dataset columns:
0 qty_dot_url
1 qty_hyphen_url
2 qty_underline_url
3 qty_slash_url
4 qty_questionmark_url
5 qty_equal_url
6 qty_at_url
7 qty_and_url
8 qty_exclamation_url
9 qty_space_url
10 qty_tilde_url
11 qty_comma_url
12 qty_plus_url
13 qty_asterisk_url
14 qty_hashtag_url
15 qty_dollar_url
16 qty_percent_url
17 qty_tld_url
18 length_url
19 qty_dot_domain
20 qty_hyphen_domain
21 qty_underline_domain
22 qty_slash_domain
23 qty_questionmark_domain
24 qty_equal_domain
25 qty_at_domain
26 qty_and_domain
27 qty_exclamation_domain
28 qty_space_domain
29 qty_tilde_domain
30 qty_comma_domain
31 qty_plus_domain
32 qty_asterisk_domain
33 qty_hashtag_domain
34 qty_dollar_domain
35 qty_percent_domain
36 qty_vowels_domain
37 domain_length
38 domain_in_ip
39 server_client_domain
40 qty_dot_directory
41 qty_hyphen_directory
42 qty_underline_directory
43 qty_slash_directory
44 qty_questionmark_directory
45 qty_equal_directory
46 qty_at_directory
47 qty_and_directory
48 qty_exclamation_directory
49 qty_space_directory
50 qty_tilde_directory
51 qty_comma_directory
52 qty_plus_directory
53 qty_asterisk_directory
54 qty_hashtag_directory
55 qty_dollar_directory
56 qty_percent_directory
57 directory_length
58 qty_dot_file
59 qty_hyphen_file
60 qty_underline_file
61 qty_slash_file
62 qty_questionmark_file
63 qty_equal_file
64 qty_at_file
65 qty_and_file
66 qty_exclamation_file
67 qty_space_file
68 qty_tilde_file
69 qty_comma_file
70 qty_plus_file
71 qty_asterisk_file
72 qty_hashtag_file
73 qty_dollar_file
74 qty_percent_file
75 file_length
76 qty_dot_params
77 qty_hyphen_params
78 qty_underline_params
79 qty_slash_params
80 qty_questionmark_params
81 qty_equal_params
82 qty_at_params
83 qty_and_params
84 qty_exclamation_params
85 qty_space_params
86 qty_tilde_params
87 qty_comma_params
88 qty_plus_params
89 qty_asterisk_params
90 qty_hashtag_params
91 qty_dollar_params
92 qty_percent_params
93 params_length
94 tld_present_params
95 qty_params
96 email_in_url
97 time_response
98 domain_spf
99 asn_ip
100 time_domain_activation
101 time_domain_expiration
102 qty_ip_resolved
103 qty_nameservers
104 qty_mx_servers
105 ttl_hostname
106 tls_ssl_certificate
107 qty_redirects
108 url_google_index
109 domain_google_index
110 url_shortened
111 phishing

In [11]:
# 1. Inspect all column names
print("COLUMN NAMES")
print(df.columns.tolist())

# 2. Check data types and non-null values
print("\nDATASET INFORMATION")
df.info()

# 3. Count missing values
print("\nMISSING VALUES")
print("Total missing values:", df.isnull().sum().sum())
print(df.isnull().sum()[df.isnull().sum() > 0])

# 4. Count duplicate rows
print("\nDUPLICATE ROWS")
print(df.duplicated().sum())

# 5. Display the last five columns
print("\nLAST FIVE COLUMNS")
display(df.iloc[:, -5:].head())

COLUMN NAMES
['qty_dot_url', 'qty_hyphen_url', 'qty_underline_url', 'qty_slash_url', 'qty_questionmark_url', 'qty_equal_url', 'qty_at_url', 'qty_and_url', 'qty_exclamation_url', 'qty_space_url', 'qty_tilde_url', 'qty_comma_url', 'qty_plus_url', 'qty_asterisk_url', 'qty_hashtag_url', 'qty_dollar_url', 'qty_percent_url', 'qty_tld_url', 'length_url', 'qty_dot_domain', 'qty_hyphen_domain', 'qty_underline_domain', 'qty_slash_domain', 'qty_questionmark_domain', 'qty_equal_domain', 'qty_at_domain', 'qty_and_domain', 'qty_exclamation_domain', 'qty_space_domain', 'qty_tilde_domain', 'qty_comma_domain', 'qty_plus_domain', 'qty_asterisk_domain', 'qty_hashtag_domain', 'qty_dollar_domain', 'qty_percent_domain', 'qty_vowels_domain', 'domain_length', 'domain_in_ip', 'server_client_domain', 'qty_dot_directory', 'qty_hyphen_directory', 'qty_underline_directory', 'qty_slash_directory', 'qty_questionmark_directory', 'qty_equal_directory', 'qty_at_directory', 'qty_and_directory', 'qty_exclamation_directory', 'qty_space_directory', 'qty_tilde_directory', 'qty_comma_directory', 'qty_plus_directory', 'qty_asterisk_directory', 'qty_hashtag_directory', 'qty_dollar_directory', 'qty_percent_directory', 'directory_length', 'qty_dot_file', 'qty_hyphen_file', 'qty_underline_file', 'qty_slash_file', 'qty_questionmark_file', 'qty_equal_file', 'qty_at_file', 'qty_and_file', 'qty_exclamation_file', 'qty_space_file', 'qty_tilde_file', 'qty_comma_file', 'qty_plus_file', 'qty_asterisk_file', 'qty_hashtag_file', 'qty_dollar_file', 'qty_percent_file', 'file_length', 'qty_dot_params', 'qty_hyphen_params', 'qty_underline_params', 'qty_slash_params', 'qty_questionmark_params', 'qty_equal_params', 'qty_at_params', 'qty_and_params', 'qty_exclamation_params', 'qty_space_params', 'qty_tilde_params', 'qty_comma_params', 'qty_plus_params', 'qty_asterisk_params', 'qty_hashtag_params', 'qty_dollar_params', 'qty_percent_params', 'params_length', 'tld_present_params', 'qty_params', 'email_in_url', 'time_response', 'domain_spf', 'asn_ip', 'time_domain_activation', 'time_domain_expiration', 'qty_ip_resolved', 'qty_nameservers', 'qty_mx_servers', 'ttl_hostname', 'tls_ssl_certificate', 'qty_redirects', 'url_google_index', 'domain_google_index', 'url_shortened', 'phishing']

DATASET INFORMATION
<class 'pandas.DataFrame'>
RangeIndex: 88647 entries, 0 to 88646
Columns: 112 entries, qty_dot_url to phishing
dtypes: float64(1), int64(111)
memory usage: 75.7 MB

MISSING VALUES
Total missing values: 0
Series([], dtype: int64)

DUPLICATE ROWS
1438

LAST FIVE COLUMNS

,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,0,0,0,0,1
1,0,0,0,0,1
2,0,0,0,0,0
3,0,0,0,0,1
4,1,0,0,0,0

In [12]:

# 1. Check the phishing label values
print("Phishing label counts:")
print(df["phishing"].value_counts(dropna=False))

print("\nPhishing label proportions:")
print(df["phishing"].value_counts(normalize=True).round(4))

# 2. Check the target data type
print("\nTarget data type:")
print(df["phishing"].dtype)

# 3. Inspect duplicate records
duplicate_rows = df[df.duplicated(keep=False)]

print("\nRows involved in duplicates:", len(duplicate_rows))
display(duplicate_rows.head(10))

# 4. Check whether duplicate feature rows have conflicting labels
feature_columns = df.columns.drop("phishing")

duplicate_features = df[
    df.duplicated(subset=feature_columns, keep=False)
]

print("\nRows with identical features, including repeated rows:")
display(duplicate_features.head(10))

Phishing label counts:
phishing
0    58000
1    30647
Name: count, dtype: int64

Phishing label proportions:
phishing
0    0.6543
1    0.3457
Name: proportion, dtype: float64

Target data type:
int64

Rows involved in duplicates: 1926

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
124,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
195,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
234,2,0,0,0,0,0,0,0,0,0,...,-1,0,0,-1,0,-1,0,0,0,0
297,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
341,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
366,3,0,0,0,0,0,0,0,0,0,...,-1,2,0,-1,0,-1,0,0,0,0
385,2,0,0,0,0,0,0,0,0,0,...,-1,2,0,-1,0,-1,0,0,0,0
440,2,0,0,0,0,0,0,0,0,0,...,-1,0,0,-1,0,-1,-1,-1,0,0
476,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
500,1,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0

Rows with identical features, including repeated rows:

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
124,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
195,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
234,2,0,0,0,0,0,0,0,0,0,...,-1,0,0,-1,0,-1,0,0,0,0
297,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
341,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
366,3,0,0,0,0,0,0,0,0,0,...,-1,2,0,-1,0,-1,0,0,0,0
385,2,0,0,0,0,0,0,0,0,0,...,-1,2,0,-1,0,-1,0,0,0,0
440,2,0,0,0,0,0,0,0,0,0,...,-1,0,0,-1,0,-1,-1,-1,0,0
476,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
500,1,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0

In [13]:

# Identify repeated feature combinations
feature_columns = df.columns.drop("phishing")

feature_groups = df.groupby(
    list(feature_columns),
    dropna=False
)["phishing"].agg(["size", "nunique"])

# Count repeated groups and groups with conflicting labels
repeated_groups = feature_groups[feature_groups["size"] > 1]

conflicting_groups = repeated_groups[
    repeated_groups["nunique"] > 1
]

print("Repeated feature groups:", len(repeated_groups))
print("Groups with conflicting labels:", len(conflicting_groups))
print("\nExamples of conflicting groups:")
display(conflicting_groups.head(10))

Repeated feature groups: 493
Groups with conflicting labels: 6

Examples of conflicting groups:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            size  \
qty_dot_url qty_hyphen_url qty_underline_url qty_slash_url qty_questionmark_url qty_equal_url qty_at_url qty_and_url qty_exclamation_url qty_space_url qty_tilde_url qty_comma_url qty_plus_url qty_asterisk_url qty_hashtag_url qty_dollar_url qty_percent_url qty_tld_url length_url qty_dot_domain qty_hyphen_domain qty_underline_domain qty_slash_domain qty_questionmark_domain qty_equal_domain qty_at_domain qty_and_domain qty_exclamation_domain qty_space_domain qty_tilde_domain qty_comma_domain qty_plus_domain qty_asterisk_domain qty_hashtag_domain qty_dollar_domain qty_percent_domain qty_vowels_domain domain_length domain_in_ip server_client_domain qty_dot_directory qty_hyphen_directory qty_underline_directory qty_slash_directory qty_questionmark_directory qty_equal_directory qty_at_directory qty_and_directory qty_exclamation_directory qty_space_directory qty_tilde_directory qty_comma_directory qty_plus_directory qty_asterisk_directory qty_hashtag_directory qty_dollar_directory qty_percent_directory directory_length qty_dot_file qty_hyphen_file qty_underline_file qty_slash_file qty_questionmark_file qty_equal_file qty_at_file qty_and_file qty_exclamation_file qty_space_file qty_tilde_file qty_comma_file qty_plus_file qty_asterisk_file qty_hashtag_file qty_dollar_file qty_percent_file file_length qty_dot_params qty_hyphen_params qty_underline_params qty_slash_params qty_questionmark_params qty_equal_params qty_at_params qty_and_params qty_exclamation_params qty_space_params qty_tilde_params qty_comma_params qty_plus_params qty_asterisk_params qty_hashtag_params qty_dollar_params qty_percent_params params_length tld_present_params qty_params email_in_url time_response domain_spf asn_ip time_domain_activation time_domain_expiration qty_ip_resolved qty_nameservers qty_mx_servers ttl_hostname tls_ssl_certificate qty_redirects url_google_index domain_google_index url_shortened
1           0              0                 0             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           10         1              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  2                 10            0            0                    -1                -1                   -1                      -1                  -1                         -1                  -1               -1                -1                        -1                  -1                  -1                  -1                 -1                     -1                    -1                   -1                    -1               -1           -1              -1                 -1             -1                    -1             -1          -1           -1                   -1             -1             -1             -1            -1                -1               -1              -1               -1          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                 3
                                             1             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           15         1              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  4                 14            0            0                     0                 0                    0                       1                   0                          0                   0                0                 0                         0                   0                   0                   0                  0                      0                     0                    0                     1                0            0               0                  0              0                     0              0           0            0                    0              0              0              0             0                 0                0               0                0          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                 2
2           0              0                 0             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           24         2              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  8                 24            0            0                    -1                -1                   -1                      -1                  -1                         -1                  -1               -1                -1                        -1                  -1                  -1                  -1                 -1                     -1                    -1                   -1                    -1               -1           -1              -1                 -1             -1                    -1             -1          -1           -1                   -1             -1             -1             -1            -1                -1               -1              -1               -1          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                 2
                                             1             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           20         2              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  5                 19            0            0                     0                 0                    0                       1                   0                          0                   0                0                 0                         0                   0                   0                   0                  0                      0                     0                    0                     1                0            0               0                  0              0                     0              0           0            0                    0              0              0              0             0                 0                0               0                0          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                 2
                                                                                                                                                                                                                                                                            24         2              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  9                 23            0            0                     0                 0                    0                       1                   0                          0                   0                0                 0                         0                   0                   0                   0                  0                      0                     0                    0                     1                0            0               0                  0              0                     0              0           0            0                    0              0              0              0             0                 0                0               0                0          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              0               0              -1           0                   -1            0                0                   0                 2
            1              0                 1             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           19         2              1                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  4                 18            0            0                     0                 0                    0                       1                   0                          0                   0                0                 0                         0                   0                   0                   0                  0                      0                     0                    0                     1                0            0               0                  0              0                     0              0           0            0                    0              0              0              0             0                 0                0               0                0          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                 2

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nunique
qty_dot_url qty_hyphen_url qty_underline_url qty_slash_url qty_questionmark_url qty_equal_url qty_at_url qty_and_url qty_exclamation_url qty_space_url qty_tilde_url qty_comma_url qty_plus_url qty_asterisk_url qty_hashtag_url qty_dollar_url qty_percent_url qty_tld_url length_url qty_dot_domain qty_hyphen_domain qty_underline_domain qty_slash_domain qty_questionmark_domain qty_equal_domain qty_at_domain qty_and_domain qty_exclamation_domain qty_space_domain qty_tilde_domain qty_comma_domain qty_plus_domain qty_asterisk_domain qty_hashtag_domain qty_dollar_domain qty_percent_domain qty_vowels_domain domain_length domain_in_ip server_client_domain qty_dot_directory qty_hyphen_directory qty_underline_directory qty_slash_directory qty_questionmark_directory qty_equal_directory qty_at_directory qty_and_directory qty_exclamation_directory qty_space_directory qty_tilde_directory qty_comma_directory qty_plus_directory qty_asterisk_directory qty_hashtag_directory qty_dollar_directory qty_percent_directory directory_length qty_dot_file qty_hyphen_file qty_underline_file qty_slash_file qty_questionmark_file qty_equal_file qty_at_file qty_and_file qty_exclamation_file qty_space_file qty_tilde_file qty_comma_file qty_plus_file qty_asterisk_file qty_hashtag_file qty_dollar_file qty_percent_file file_length qty_dot_params qty_hyphen_params qty_underline_params qty_slash_params qty_questionmark_params qty_equal_params qty_at_params qty_and_params qty_exclamation_params qty_space_params qty_tilde_params qty_comma_params qty_plus_params qty_asterisk_params qty_hashtag_params qty_dollar_params qty_percent_params params_length tld_present_params qty_params email_in_url time_response domain_spf asn_ip time_domain_activation time_domain_expiration qty_ip_resolved qty_nameservers qty_mx_servers ttl_hostname tls_ssl_certificate qty_redirects url_google_index domain_google_index url_shortened

In [14]:

# Find the groups with conflicting phishing labels
conflicting_groups = feature_groups[
    (feature_groups["size"] > 1) &
    (feature_groups["nunique"] > 1)
]

print("Number of conflicting groups:", len(conflicting_groups))
print("Total rows in conflicting groups:", conflicting_groups["size"].sum())

print("\nConflicting group details:")
display(conflicting_groups)

# Inspect the original records in those groups
conflicting_index = df.set_index(
    list(feature_columns)
).index.isin(
    conflicting_groups.index
)

conflicting_rows = df.loc[conflicting_index]

print("\nOriginal records involved:")
display(conflicting_rows[["phishing"]].head(20))

Number of conflicting groups: 6
Total rows in conflicting groups: 13

Conflicting group details:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            size  \
qty_dot_url qty_hyphen_url qty_underline_url qty_slash_url qty_questionmark_url qty_equal_url qty_at_url qty_and_url qty_exclamation_url qty_space_url qty_tilde_url qty_comma_url qty_plus_url qty_asterisk_url qty_hashtag_url qty_dollar_url qty_percent_url qty_tld_url length_url qty_dot_domain qty_hyphen_domain qty_underline_domain qty_slash_domain qty_questionmark_domain qty_equal_domain qty_at_domain qty_and_domain qty_exclamation_domain qty_space_domain qty_tilde_domain qty_comma_domain qty_plus_domain qty_asterisk_domain qty_hashtag_domain qty_dollar_domain qty_percent_domain qty_vowels_domain domain_length domain_in_ip server_client_domain qty_dot_directory qty_hyphen_directory qty_underline_directory qty_slash_directory qty_questionmark_directory qty_equal_directory qty_at_directory qty_and_directory qty_exclamation_directory qty_space_directory qty_tilde_directory qty_comma_directory qty_plus_directory qty_asterisk_directory qty_hashtag_directory qty_dollar_directory qty_percent_directory directory_length qty_dot_file qty_hyphen_file qty_underline_file qty_slash_file qty_questionmark_file qty_equal_file qty_at_file qty_and_file qty_exclamation_file qty_space_file qty_tilde_file qty_comma_file qty_plus_file qty_asterisk_file qty_hashtag_file qty_dollar_file qty_percent_file file_length qty_dot_params qty_hyphen_params qty_underline_params qty_slash_params qty_questionmark_params qty_equal_params qty_at_params qty_and_params qty_exclamation_params qty_space_params qty_tilde_params qty_comma_params qty_plus_params qty_asterisk_params qty_hashtag_params qty_dollar_params qty_percent_params params_length tld_present_params qty_params email_in_url time_response domain_spf asn_ip time_domain_activation time_domain_expiration qty_ip_resolved qty_nameservers qty_mx_servers ttl_hostname tls_ssl_certificate qty_redirects url_google_index domain_google_index url_shortened
1           0              0                 0             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           10         1              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  2                 10            0            0                    -1                -1                   -1                      -1                  -1                         -1                  -1               -1                -1                        -1                  -1                  -1                  -1                 -1                     -1                    -1                   -1                    -1               -1           -1              -1                 -1             -1                    -1             -1          -1           -1                   -1             -1             -1             -1            -1                -1               -1              -1               -1          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                 3
                                             1             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           15         1              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  4                 14            0            0                     0                 0                    0                       1                   0                          0                   0                0                 0                         0                   0                   0                   0                  0                      0                     0                    0                     1                0            0               0                  0              0                     0              0           0            0                    0              0              0              0             0                 0                0               0                0          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                 2
2           0              0                 0             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           24         2              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  8                 24            0            0                    -1                -1                   -1                      -1                  -1                         -1                  -1               -1                -1                        -1                  -1                  -1                  -1                 -1                     -1                    -1                   -1                    -1               -1           -1              -1                 -1             -1                    -1             -1          -1           -1                   -1             -1             -1             -1            -1                -1               -1              -1               -1          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                 2
                                             1             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           20         2              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  5                 19            0            0                     0                 0                    0                       1                   0                          0                   0                0                 0                         0                   0                   0                   0                  0                      0                     0                    0                     1                0            0               0                  0              0                     0              0           0            0                    0              0              0              0             0                 0                0               0                0          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                 2
                                                                                                                                                                                                                                                                            24         2              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  9                 23            0            0                     0                 0                    0                       1                   0                          0                   0                0                 0                         0                   0                   0                   0                  0                      0                     0                    0                     1                0            0               0                  0              0                     0              0           0            0                    0              0              0              0             0                 0                0               0                0          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              0               0              -1           0                   -1            0                0                   0                 2
            1              0                 1             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           19         2              1                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  4                 18            0            0                     0                 0                    0                       1                   0                          0                   0                0                 0                         0                   0                   0                   0                  0                      0                     0                    0                     1                0            0               0                  0              0                     0              0           0            0                    0              0              0              0             0                 0                0               0                0          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                 2

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nunique
qty_dot_url qty_hyphen_url qty_underline_url qty_slash_url qty_questionmark_url qty_equal_url qty_at_url qty_and_url qty_exclamation_url qty_space_url qty_tilde_url qty_comma_url qty_plus_url qty_asterisk_url qty_hashtag_url qty_dollar_url qty_percent_url qty_tld_url length_url qty_dot_domain qty_hyphen_domain qty_underline_domain qty_slash_domain qty_questionmark_domain qty_equal_domain qty_at_domain qty_and_domain qty_exclamation_domain qty_space_domain qty_tilde_domain qty_comma_domain qty_plus_domain qty_asterisk_domain qty_hashtag_domain qty_dollar_domain qty_percent_domain qty_vowels_domain domain_length domain_in_ip server_client_domain qty_dot_directory qty_hyphen_directory qty_underline_directory qty_slash_directory qty_questionmark_directory qty_equal_directory qty_at_directory qty_and_directory qty_exclamation_directory qty_space_directory qty_tilde_directory qty_comma_directory qty_plus_directory qty_asterisk_directory qty_hashtag_directory qty_dollar_directory qty_percent_directory directory_length qty_dot_file qty_hyphen_file qty_underline_file qty_slash_file qty_questionmark_file qty_equal_file qty_at_file qty_and_file qty_exclamation_file qty_space_file qty_tilde_file qty_comma_file qty_plus_file qty_asterisk_file qty_hashtag_file qty_dollar_file qty_percent_file file_length qty_dot_params qty_hyphen_params qty_underline_params qty_slash_params qty_questionmark_params qty_equal_params qty_at_params qty_and_params qty_exclamation_params qty_space_params qty_tilde_params qty_comma_params qty_plus_params qty_asterisk_params qty_hashtag_params qty_dollar_params qty_percent_params params_length tld_present_params qty_params email_in_url time_response domain_spf asn_ip time_domain_activation time_domain_expiration qty_ip_resolved qty_nameservers qty_mx_servers ttl_hostname tls_ssl_certificate qty_redirects url_google_index domain_google_index url_shortened

Original records involved:

       phishing
2209          1
2948          1
5611          0
9436          0
13342         1
34768         0
60583         1
60928         0
61429         0
64527         1
70733         1
72830         0
80424         0

In [15]:

# Show the conflicting label counts for each feature group
conflict_details = (
    df.groupby(list(feature_columns), dropna=False)["phishing"]
    .agg(
        total_rows="size",
        unique_labels="nunique",
        label_values=lambda labels: sorted(labels.unique().tolist())
    )
    .query("unique_labels > 1")
)

display(conflict_details)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            total_rows  \
qty_dot_url qty_hyphen_url qty_underline_url qty_slash_url qty_questionmark_url qty_equal_url qty_at_url qty_and_url qty_exclamation_url qty_space_url qty_tilde_url qty_comma_url qty_plus_url qty_asterisk_url qty_hashtag_url qty_dollar_url qty_percent_url qty_tld_url length_url qty_dot_domain qty_hyphen_domain qty_underline_domain qty_slash_domain qty_questionmark_domain qty_equal_domain qty_at_domain qty_and_domain qty_exclamation_domain qty_space_domain qty_tilde_domain qty_comma_domain qty_plus_domain qty_asterisk_domain qty_hashtag_domain qty_dollar_domain qty_percent_domain qty_vowels_domain domain_length domain_in_ip server_client_domain qty_dot_directory qty_hyphen_directory qty_underline_directory qty_slash_directory qty_questionmark_directory qty_equal_directory qty_at_directory qty_and_directory qty_exclamation_directory qty_space_directory qty_tilde_directory qty_comma_directory qty_plus_directory qty_asterisk_directory qty_hashtag_directory qty_dollar_directory qty_percent_directory directory_length qty_dot_file qty_hyphen_file qty_underline_file qty_slash_file qty_questionmark_file qty_equal_file qty_at_file qty_and_file qty_exclamation_file qty_space_file qty_tilde_file qty_comma_file qty_plus_file qty_asterisk_file qty_hashtag_file qty_dollar_file qty_percent_file file_length qty_dot_params qty_hyphen_params qty_underline_params qty_slash_params qty_questionmark_params qty_equal_params qty_at_params qty_and_params qty_exclamation_params qty_space_params qty_tilde_params qty_comma_params qty_plus_params qty_asterisk_params qty_hashtag_params qty_dollar_params qty_percent_params params_length tld_present_params qty_params email_in_url time_response domain_spf asn_ip time_domain_activation time_domain_expiration qty_ip_resolved qty_nameservers qty_mx_servers ttl_hostname tls_ssl_certificate qty_redirects url_google_index domain_google_index url_shortened
1           0              0                 0             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           10         1              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  2                 10            0            0                    -1                -1                   -1                      -1                  -1                         -1                  -1               -1                -1                        -1                  -1                  -1                  -1                 -1                     -1                    -1                   -1                    -1               -1           -1              -1                 -1             -1                    -1             -1          -1           -1                   -1             -1             -1             -1            -1                -1               -1              -1               -1          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                       3
                                             1             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           15         1              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  4                 14            0            0                     0                 0                    0                       1                   0                          0                   0                0                 0                         0                   0                   0                   0                  0                      0                     0                    0                     1                0            0               0                  0              0                     0              0           0            0                    0              0              0              0             0                 0                0               0                0          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                       2
2           0              0                 0             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           24         2              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  8                 24            0            0                    -1                -1                   -1                      -1                  -1                         -1                  -1               -1                -1                        -1                  -1                  -1                  -1                 -1                     -1                    -1                   -1                    -1               -1           -1              -1                 -1             -1                    -1             -1          -1           -1                   -1             -1             -1             -1            -1                -1               -1              -1               -1          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                       2
                                             1             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           20         2              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  5                 19            0            0                     0                 0                    0                       1                   0                          0                   0                0                 0                         0                   0                   0                   0                  0                      0                     0                    0                     1                0            0               0                  0              0                     0              0           0            0                    0              0              0              0             0                 0                0               0                0          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                       2
                                                                                                                                                                                                                                                                            24         2              0                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  9                 23            0            0                     0                 0                    0                       1                   0                          0                   0                0                 0                         0                   0                   0                   0                  0                      0                     0                    0                     1                0            0               0                  0              0                     0              0           0            0                    0              0              0              0             0                 0                0               0                0          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              0               0              -1           0                   -1            0                0                   0                       2
            1              0                 1             0                    0             0          0           0                   0             0             0             0            0                0               0              0               1           19         2              1                 0                    0                0                       0                0             0              0                      0                0                0                0               0                   0                  0                 0                  4                 18            0            0                     0                 0                    0                       1                   0                          0                   0                0                 0                         0                   0                   0                   0                  0                      0                     0                    0                     1                0            0               0                  0              0                     0              0           0            0                    0              0              0              0             0                 0                0               0                0          -1             -1                -1                   -1               -1                      -1               -1            -1             -1                     -1               -1               -1               -1              -1                  -1                 -1                -1                 -1            -1                 -1         0            -1.0          0          -1     -1                     -1                     -1              4               0              -1           0                   -1            0                0                   0                       2

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            unique_labels  \
qty_dot_url qty_hyphen_url qty_underline_url qty_slash_url qty_questionmark_url qty_equal_url qty_at_url qty_and_url qty_exclamation_url qty_space_url qty_tilde_url qty_comma_url qty_plus_url qty_asterisk_url qty_hashtag_url qty_dollar_url qty_percent_url qty_tld_url length_url qty_dot_domain qty_hyphen_domain qty_underline_domain qty_slash_domain qty_questionmark_domain qty_equal_domain qty_at_domain qty_and_domain qty_exclamation_domain qty_space_domain qty_tilde_domain qty_comma_domain qty_plus_domain qty_asterisk_domain qty_hashtag_domain qty_dollar_domain qty_percent_domain qty_vowels_domain domain_length domain_in_ip server_client_domain qty_dot_directory qty_hyphen_directory qty_underline_directory qty_slash_directory qty_questionmark_directory qty_equal_directory qty_at_directory qty_and_directory qty_exclamation_directory qty_space_directory qty_tilde_directory qty_comma_directory qty_plus_directory qty_asterisk_directory qty_hashtag_directory qty_dollar_directory qty_percent_directory directory_length qty_dot_file qty_hyphen_file qty_underline_file qty_slash_file qty_questionmark_file qty_equal_file qty_at_file qty_and_file qty_exclamation_file qty_space_file qty_tilde_file qty_comma_file qty_plus_file qty_asterisk_file qty_hashtag_file qty_dollar_file qty_percent_file file_length qty_dot_params qty_hyphen_params qty_underline_params qty_slash_params qty_questionmark_params qty_equal_params qty_at_params qty_and_params qty_exclamation_params qty_space_params qty_tilde_params qty_comma_params qty_plus_params qty_asterisk_params qty_hashtag_params qty_dollar_params qty_percent_params params_length tld_present_params qty_params email_in_url time_response domain_spf asn_ip time_domain_activation time_domain_expiration qty_ip_resolved qty_nameservers qty_mx_servers ttl_hostname tls_ssl_certificate qty_redirects url_google_index domain_google_index url_shortened

In [16]:

# Count -1 values in each column
minus_one_counts = (df == -1).sum().sort_values(ascending=False)

print("Columns containing -1 values:")
display(minus_one_counts[minus_one_counts > 0])

print("\nTotal -1 values in dataset:", int((df == -1).sum().sum()))

# Check the target labels again
print("\nTarget label counts:")
display(df["phishing"].value_counts())

Columns containing -1 values:

qty_questionmark_params    81225
qty_equal_params           81225
qty_at_params              81225
qty_and_params             81225
qty_exclamation_params     81225
                           ...
time_response               5860
ttl_hostname                4454
qty_ip_resolved             4453
url_google_index              90
domain_google_index           88
Length: 66, dtype: int64

Total -1 values in dataset: 3428432

Target label counts:

phishing
0    58000
1    30647
Name: count, dtype: int64

In [17]:

# Inspect columns with the most -1 values
minus_one_counts = (df == -1).sum().sort_values(ascending=False)

summary = pd.DataFrame({
    "minus_one_count": minus_one_counts,
    "minus_one_percentage": (minus_one_counts / len(df) * 100).round(2)
})

display(summary.head(20))

# Inspect selected rows with many -1 values
display(df.loc[(df == -1).sum(axis=1) > 50].head(5))

                         minus_one_count  minus_one_percentage
qty_questionmark_params            81225                 91.63
qty_equal_params                   81225                 91.63
qty_at_params                      81225                 91.63
qty_and_params                     81225                 91.63
qty_exclamation_params             81225                 91.63
qty_space_params                   81225                 91.63
qty_tilde_params                   81225                 91.63
qty_comma_params                   81225                 91.63
qty_plus_params                    81225                 91.63
qty_asterisk_params                81225                 91.63
qty_hashtag_params                 81225                 91.63
qty_dollar_params                  81225                 91.63
qty_dot_params                     81225                 91.63
qty_hyphen_params                  81225                 91.63
qty_underline_params               81225                 91.63
qty_slash_params                   81225                 91.63
qty_percent_params                 81225                 91.63
params_length                      81225                 91.63
tld_present_params                 81225                 91.63
qty_params                         81225                 91.63

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
4,2,0,0,0,0,0,0,0,0,0,...,1,2,1,3597,0,1,0,0,0,0
6,2,0,0,0,0,0,0,0,0,0,...,1,2,2,291,0,0,0,0,0,0
8,2,0,0,0,0,0,0,0,0,0,...,1,4,2,3596,1,1,0,0,0,0
10,2,1,0,0,0,0,0,0,0,0,...,1,2,1,43197,0,1,0,0,0,0
13,2,0,0,0,0,0,0,0,0,0,...,1,2,1,14396,1,0,0,0,0,0

In [18]:

# Check the dataset file and column data types
print("Dataset columns:", len(df.columns))
print("\nData types:")
print(df.dtypes.value_counts())

# Check parameter features on rows where qty_params is -1
parameter_columns = [
    col for col in df.columns
    if col.endswith("_params") or col == "params_length"
]

print("\nRows where qty_params == -1:")
display(df.loc[df["qty_params"] == -1, parameter_columns].head(10))

# Compare with rows where qty_params is not -1
print("\nRows where qty_params != -1:")
display(df.loc[df["qty_params"] != -1, parameter_columns].head(10))

Dataset columns: 112

Data types:
int64      111
float64      1
Name: count, dtype: int64

Rows where qty_params == -1:

,qty_dot_params,qty_hyphen_params,qty_underline_params,qty_slash_params,qty_questionmark_params,qty_equal_params,qty_at_params,qty_and_params,qty_exclamation_params,qty_space_params,qty_tilde_params,qty_comma_params,qty_plus_params,qty_asterisk_params,qty_hashtag_params,qty_dollar_params,qty_percent_params,params_length,tld_present_params,qty_params
0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
5,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
6,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
7,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
8,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
9,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
10,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

Rows where qty_params != -1:

,qty_dot_params,qty_hyphen_params,qty_underline_params,qty_slash_params,qty_questionmark_params,qty_equal_params,qty_at_params,qty_and_params,qty_exclamation_params,qty_space_params,qty_tilde_params,qty_comma_params,qty_plus_params,qty_asterisk_params,qty_hashtag_params,qty_dollar_params,qty_percent_params,params_length,tld_present_params,qty_params
1,0,0,1,0,0,3,0,2,0,0,0,0,0,0,0,0,0,165,0,3
15,0,0,1,0,0,3,0,2,0,0,0,0,0,0,0,0,0,165,0,3
18,2,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,26,1,1
39,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,24,1,1
50,0,0,0,0,0,3,0,2,0,0,0,0,0,0,0,0,0,46,0,3
51,1,0,2,0,0,3,0,2,0,0,0,0,0,0,0,0,0,53,1,3
53,0,0,1,0,0,3,0,2,0,0,0,0,0,0,0,0,0,165,0,3
61,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,33,0,1
68,0,0,1,0,0,3,0,2,0,0,0,0,0,0,0,0,0,165,0,3
71,2,0,0,0,0,4,0,3,0,0,0,0,0,0,0,0,12,241,1,4

In [19]:

# Count how often -1 appears in each column
minus_one_counts = (df == -1).sum()

# Calculate the percentage of rows containing -1
minus_one_percentages = (df == -1).mean() * 100

# Combine the results into a summary table
minus_one_summary = pd.DataFrame({
    "minus_one_count": minus_one_counts,
    "minus_one_percentage": minus_one_percentages
})

# Show columns where -1 occurs at least once, from highest to lowest
minus_one_summary = (
    minus_one_summary[minus_one_summary["minus_one_count"] > 0]
    .sort_values("minus_one_percentage", ascending=False)
)

display(minus_one_summary.head(30))

                            minus_one_count  minus_one_percentage
qty_dollar_params                     81225             91.627466
qty_hashtag_params                    81225             91.627466
qty_underline_params                  81225             91.627466
qty_slash_params                      81225             91.627466
qty_asterisk_params                   81225             91.627466
qty_plus_params                       81225             91.627466
qty_space_params                      81225             91.627466
qty_exclamation_params                81225             91.627466
qty_comma_params                      81225             91.627466
qty_tilde_params                      81225             91.627466
qty_at_params                         81225             91.627466
qty_and_params                        81225             91.627466
qty_equal_params                      81225             91.627466
qty_questionmark_params               81225             91.627466
params_length                         81225             91.627466
qty_percent_params                    81225             91.627466
qty_params                            81225             91.627466
tld_present_params                    81225             91.627466
qty_dot_params                        81225             91.627466
qty_hyphen_params                     81225             91.627466
qty_hyphen_directory                  47509             53.593466
qty_dot_directory                     47509             53.593466
qty_underline_directory               47509             53.593466
qty_slash_directory                   47509             53.593466
qty_questionmark_directory            47509             53.593466
qty_equal_directory                   47509             53.593466
qty_tilde_directory                   47509             53.593466
qty_comma_directory                   47509             53.593466
qty_plus_directory                    47509             53.593466
qty_asterisk_directory                47509             53.593466

In [20]:

# Check the target label distribution
print("Target label counts:")
display(df["phishing"].value_counts().sort_index())

print("\nTarget label percentages:")
display(
    (df["phishing"].value_counts(normalize=True).sort_index() * 100)
    .round(2)
)

Target label counts:

phishing
0    58000
1    30647
Name: count, dtype: int64

Target label percentages:

phishing
0    65.43
1    34.57
Name: proportion, dtype: float64

In [21]:

# Check -1 values across URL feature groups
feature_groups = {
    "URL": [c for c in df.columns if c.endswith("_url")],
    "Domain": [c for c in df.columns if c.endswith("_domain")],
    "Directory": [c for c in df.columns if c.endswith("_directory")],
    "File": [c for c in df.columns if c.endswith("_file")],
    "Parameters": [c for c in df.columns if c.endswith("_params")],
    "Other": [
        c for c in df.columns
        if not any(
            c.endswith(suffix)
            for suffix in [
                "_url", "_domain", "_directory", "_file", "_params"
            ]
        )
        and c != "phishing"
    ]
}

for group, columns in feature_groups.items():
    if columns:
        count = (df[columns] == -1).sum().sum()
        total = df[columns].size
        print(
            f"{group}: {count:,} values equal to -1 "
            f"out of {total:,} feature values "
            f"({count / total * 100:.2f}%)"
        )

URL: 0 values equal to -1 out of 1,772,940 feature values (0.00%)
Domain: 0 values equal to -1 out of 1,684,293 feature values (0.00%)
Directory: 807,653 values equal to -1 out of 1,506,999 feature values (53.59%)
File: 807,653 values equal to -1 out of 1,506,999 feature values (53.59%)
Parameters: 1,543,275 values equal to -1 out of 1,684,293 feature values (91.63%)
Other: 269,851 values equal to -1 out of 1,684,293 feature values (16.02%)

In [22]:

# Check -1 values across URL feature groups
feature_groups = {
    "URL": [c for c in df.columns if c.endswith("_url")],
    "Domain": [c for c in df.columns if c.endswith("_domain")],
    "Directory": [c for c in df.columns if c.endswith("_directory")],
    "File": [c for c in df.columns if c.endswith("_file")],
    "Parameters": [c for c in df.columns if c.endswith("_params")],
    "Other": [
        c for c in df.columns
        if not any(
            c.endswith(suffix)
            for suffix in [
                "_url", "_domain", "_directory", "_file", "_params"
            ]
        )
        and c != "phishing"
    ]
}

for group, columns in feature_groups.items():
    if columns:
        count = (df[columns] == -1).sum().sum()
        total = df[columns].size
        print(
            f"{group}: {count:,} values equal to -1 "
            f"out of {total:,} feature values "
            f"({count / total * 100:.2f}%)"
        )

URL: 0 values equal to -1 out of 1,772,940 feature values (0.00%)
Domain: 0 values equal to -1 out of 1,684,293 feature values (0.00%)
Directory: 807,653 values equal to -1 out of 1,506,999 feature values (53.59%)
File: 807,653 values equal to -1 out of 1,506,999 feature values (53.59%)
Parameters: 1,543,275 values equal to -1 out of 1,684,293 feature values (91.63%)
Other: 269,851 values equal to -1 out of 1,684,293 feature values (16.02%)

In [23]:

# Identify features that do not belong to the URL component groups
other_columns = [
    c for c in df.columns
    if not any(
        c.endswith(suffix)
        for suffix in [
            "_url", "_domain", "_directory", "_file", "_params"
        ]
    )
    and c != "phishing"
]

# Display how often each feature contains -1
other_summary = pd.DataFrame({
    "minus_one_count": (df[other_columns] == -1).sum(),
    "minus_one_percentage": (df[other_columns] == -1).mean() * 100
})

other_summary = other_summary.sort_values(
    "minus_one_percentage", ascending=False
)

display(other_summary.head(25))

                        minus_one_count  minus_one_percentage
params_length                     81225             91.627466
file_length                       47509             53.593466
directory_length                  47509             53.593466
time_domain_expiration            26210             29.566708
time_domain_activation            24354             27.473011
domain_spf                        14677             16.556680
qty_redirects                      6949              7.838957
asn_ip                             6473              7.301996
time_response                      5860              6.610489
ttl_hostname                       4454              5.024423
qty_ip_resolved                    4453              5.023295
url_google_index                     90              0.101526
domain_google_index                  88              0.099270
domain_in_ip                          0              0.000000
domain_length                         0              0.000000
tls_ssl_certificate                   0              0.000000
qty_mx_servers                        0              0.000000
qty_nameservers                       0              0.000000
url_shortened                         0              0.000000

In [24]:

# Features with -1 values that need further investigation
features_to_check = [
    "time_domain_expiration",
    "time_domain_activation",
    "domain_spf",
    "qty_redirects",
    "asn_ip",
    "time_response",
    "ttl_hostname",
    "qty_ip_resolved",
    "url_google_index",
    "domain_google_index"
]

# Compare the percentage of -1 values within each target class
for feature in features_to_check:
    print(f"\n{feature}")
    
    summary = (
        df.assign(has_minus_one=df[feature].eq(-1))
        .groupby("phishing")["has_minus_one"]
        .agg(["sum", "count", "mean"])
    )
    
    summary["percentage"] = (summary["mean"] * 100).round(2)
    display(summary[["sum", "count", "percentage"]])

time_domain_expiration

C:\Users\asand\AppData\Local\Temp\ipykernel_20336\453747631.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.assign(has_minus_one=df[feature].eq(-1))

            sum  count  percentage
phishing
0         14928  58000       25.74
1         11282  30647       36.81

time_domain_activation

C:\Users\asand\AppData\Local\Temp\ipykernel_20336\453747631.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.assign(has_minus_one=df[feature].eq(-1))

            sum  count  percentage
phishing
0         13492  58000       23.26
1         10862  30647       35.44

domain_spf

C:\Users\asand\AppData\Local\Temp\ipykernel_20336\453747631.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.assign(has_minus_one=df[feature].eq(-1))

           sum  count  percentage
phishing
0         7780  58000       13.41
1         6897  30647       22.50

qty_redirects

C:\Users\asand\AppData\Local\Temp\ipykernel_20336\453747631.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.assign(has_minus_one=df[feature].eq(-1))

           sum  count  percentage
phishing
0         5395  58000        9.30
1         1554  30647        5.07

asn_ip

C:\Users\asand\AppData\Local\Temp\ipykernel_20336\453747631.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.assign(has_minus_one=df[feature].eq(-1))

           sum  count  percentage
phishing
0         4925  58000        8.49
1         1548  30647        5.05

time_response

C:\Users\asand\AppData\Local\Temp\ipykernel_20336\453747631.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.assign(has_minus_one=df[feature].eq(-1))

           sum  count  percentage
phishing
0         4466  58000        7.70
1         1394  30647        4.55

ttl_hostname

C:\Users\asand\AppData\Local\Temp\ipykernel_20336\453747631.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.assign(has_minus_one=df[feature].eq(-1))

           sum  count  percentage
phishing
0         3511  58000        6.05
1          943  30647        3.08

qty_ip_resolved

C:\Users\asand\AppData\Local\Temp\ipykernel_20336\453747631.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.assign(has_minus_one=df[feature].eq(-1))

           sum  count  percentage
phishing
0         3509  58000        6.05
1          944  30647        3.08

url_google_index

C:\Users\asand\AppData\Local\Temp\ipykernel_20336\453747631.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.assign(has_minus_one=df[feature].eq(-1))

          sum  count  percentage
phishing
0          90  58000        0.16
1           0  30647        0.00

domain_google_index

C:\Users\asand\AppData\Local\Temp\ipykernel_20336\453747631.py:20: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.assign(has_minus_one=df[feature].eq(-1))

          sum  count  percentage
phishing
0          88  58000        0.15
1           0  30647        0.00

In [25]:

# Compare -1 values by target label without modifying df
for feature in features_to_check:
    print(f"\n{feature}")

    has_minus_one = df[feature].eq(-1)

    summary = pd.DataFrame({
        "minus_one_count": has_minus_one.groupby(df["phishing"]).sum(),
        "total_records": has_minus_one.groupby(df["phishing"]).size(),
        "percentage": (
            has_minus_one.groupby(df["phishing"]).mean() * 100
        ).round(2)
    })

    display(summary)

time_domain_expiration

          minus_one_count  total_records  percentage
phishing
0                   14928          58000       25.74
1                   11282          30647       36.81

time_domain_activation

          minus_one_count  total_records  percentage
phishing
0                   13492          58000       23.26
1                   10862          30647       35.44

domain_spf

          minus_one_count  total_records  percentage
phishing
0                    7780          58000       13.41
1                    6897          30647       22.50

qty_redirects

          minus_one_count  total_records  percentage
phishing
0                    5395          58000        9.30
1                    1554          30647        5.07

asn_ip

          minus_one_count  total_records  percentage
phishing
0                    4925          58000        8.49
1                    1548          30647        5.05

time_response

          minus_one_count  total_records  percentage
phishing
0                    4466          58000        7.70
1                    1394          30647        4.55

ttl_hostname

          minus_one_count  total_records  percentage
phishing
0                    3511          58000        6.05
1                     943          30647        3.08

qty_ip_resolved

          minus_one_count  total_records  percentage
phishing
0                    3509          58000        6.05
1                     944          30647        3.08

url_google_index

          minus_one_count  total_records  percentage
phishing
0                      90          58000        0.16
1                       0          30647        0.00

domain_google_index

          minus_one_count  total_records  percentage
phishing
0                      88          58000        0.15
1                       0          30647        0.00

In [26]:

# Identify identical feature sets that have conflicting target labels
feature_columns = df.columns.drop("phishing")

feature_groups = (
    df.groupby(list(feature_columns), dropna=False)["phishing"]
    .agg(["size", "nunique"])
)

conflicting_groups = feature_groups[
    (feature_groups["size"] > 1) &
    (feature_groups["nunique"] > 1)
]

print("Conflicting feature groups:", len(conflicting_groups))
print("Rows in conflicting groups:", conflicting_groups["size"].sum())

# Display the records belonging to those groups
conflict_index = df.set_index(list(feature_columns)).index.isin(
    conflicting_groups.index
)

conflict_rows = df.loc[conflict_index].sort_values(
    list(feature_columns)
)

display(conflict_rows[["phishing"]].head(20))

Conflicting feature groups: 6
Rows in conflicting groups: 13

       phishing
2209          1
34768         0
80424         0
60583         1
72830         0
60928         0
64527         1
5611          0
13342         1
9436          0
70733         1
2948          1
61429         0

In [27]:

# Get the feature combinations that have conflicting labels
conflicting_features = conflicting_groups.index

# Match all original records belonging to those feature combinations
df_indexed = df.set_index(list(feature_columns))

conflict_mask = df_indexed.index.isin(conflicting_features)
conflict_records = df_indexed.loc[conflict_mask].reset_index()

# Display the feature values and labels for all conflicting records
display(
    conflict_records.sort_values(
        list(feature_columns) + ["phishing"]
    ).reset_index(drop=True)
)

C:\Users\asand\AppData\Local\Temp\ipykernel_20336\915010260.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  conflict_records = df_indexed.loc[conflict_mask].reset_index()

,qty_dot_url,qty_hyphen_url,qty_underline_url,qty_slash_url,qty_questionmark_url,qty_equal_url,qty_at_url,qty_and_url,qty_exclamation_url,qty_space_url,...,qty_ip_resolved,qty_nameservers,qty_mx_servers,ttl_hostname,tls_ssl_certificate,qty_redirects,url_google_index,domain_google_index,url_shortened,phishing
0,1,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,1
3,1,0,0,1,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
4,1,0,0,1,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,1
5,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
6,2,0,0,0,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,1
7,2,0,0,1,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
8,2,0,0,1,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,1
9,2,0,0,1,0,0,0,0,0,0,...,-1,0,0,-1,0,-1,0,0,0,0
10,2,0,0,1,0,0,0,0,0,0,...,-1,0,0,-1,0,-1,0,0,0,1
11,2,1,0,1,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,0
12,2,1,0,1,0,0,0,0,0,0,...,-1,4,0,-1,0,-1,0,0,0,1

In [28]:

# Find conflicting feature combinations and their original row numbers
feature_columns = df.columns.drop("phishing")

conflicting_groups = (
    df.groupby(list(feature_columns), dropna=False)["phishing"]
    .agg(["size", "nunique"])
)

conflicting_groups = conflicting_groups[
    (conflicting_groups["size"] > 1) &
    (conflicting_groups["nunique"] > 1)
]

# Identify all rows that belong to the conflicting groups
indexed_features = pd.MultiIndex.from_frame(df[feature_columns])
conflict_mask = indexed_features.isin(conflicting_groups.index)

# Display a compact summary of the affected rows
conflict_summary = df.loc[conflict_mask, ["phishing"]].copy()
conflict_summary.insert(
    0, "original_row_number", conflict_summary.index
)

display(conflict_summary.sort_values("original_row_number"))

       original_row_number  phishing
2209                  2209         1
2948                  2948         1
5611                  5611         0
9436                  9436         0
13342                13342         1
34768                34768         0
60583                60583         1
60928                60928         0
61429                61429         0
64527                64527         1
70733                70733         1
72830                72830         0
80424                80424         0

In [29]:

# Preserve the original dataset and create a working copy
df_work = df.copy()

# Identify feature combinations with conflicting labels
feature_columns = df_work.columns.drop("phishing")

label_counts = (
    df_work.groupby(list(feature_columns), dropna=False)["phishing"]
    .nunique()
)

# Mark every row whose feature combination has conflicting labels
conflict_keys = label_counts[label_counts > 1].index

feature_index = pd.MultiIndex.from_frame(df_work[feature_columns])
conflict_mask = feature_index.isin(conflict_keys)

# Report the number of affected rows
print("Original dataset rows:", len(df_work))
print("Rows in conflicting groups:", int(conflict_mask.sum()))
print("Conflicting feature groups:", len(conflict_keys))

Original dataset rows: 88647
Rows in conflicting groups: 13
Conflicting feature groups: 6

In [30]:

# Identify the conflicting feature groups
feature_columns = df.columns.drop("phishing")

group_summary = (
    df.groupby(list(feature_columns), dropna=False)["phishing"]
    .agg(record_count="size", distinct_labels="nunique")
    .reset_index()
)

conflicts = group_summary[
    (group_summary["record_count"] > 1) &
    (group_summary["distinct_labels"] > 1)
].copy()

print("Number of conflicting feature groups:", len(conflicts))
print("Records across conflicting groups:", conflicts["record_count"].sum())

# Show each group's size and its conflicting labels
for group_number, (_, group) in enumerate(conflicts.iterrows(), start=1):
    features = group[feature_columns]
    mask = df[feature_columns].eq(features).all(axis=1)
    labels = sorted(df.loc[mask, "phishing"].unique().tolist())

    print(
        f"Group {group_number}: "
        f"{int(mask.sum())} records, labels = {labels}"
    )

C:\Users\asand\AppData\Local\Temp\ipykernel_20336\937460342.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()

Number of conflicting feature groups: 6
Records across conflicting groups: 13
Group 1: 3 records, labels = [0, 1]
Group 2: 2 records, labels = [0, 1]
Group 3: 2 records, labels = [0, 1]
Group 4: 2 records, labels = [0, 1]
Group 5: 2 records, labels = [0, 1]
Group 6: 2 records, labels = [0, 1]

In [31]:
print("DATA QUALITY SUMMARY")
print("-" * 35)

print(f"Total rows: {len(df):,}")
print(f"Total columns: {df.shape[1]}")
print(f"Missing values: {df.isnull().sum().sum():,}")
print(f"Exact duplicate rows: {df.duplicated().sum():,}")
print(f"Conflicting feature groups: {len(conflicts)}")
print(f"Records in conflicting groups: {conflicts['record_count'].sum():,}")

print("\nTarget distribution:")
print(df["phishing"].value_counts().sort_index())

print("\nTarget distribution (%):")
print((df["phishing"].value_counts(normalize=True).sort_index() * 100).round(2))

DATA QUALITY SUMMARY
-----------------------------------
Total rows: 88,647
Total columns: 112
Missing values: 0
Exact duplicate rows: 1,438
Conflicting feature groups: 6
Records in conflicting groups: 13

Target distribution:
phishing
0    58000
1    30647
Name: count, dtype: int64

Target distribution (%):
phishing
0    65.43
1    34.57
Name: proportion, dtype: float64

In [32]:
print("Target column:")
print("phishing")

print("\nAll column names:")
for column in df.columns:
    print(column)

print("\nTarget values:")
print(sorted(df["phishing"].unique()))

Target column:
phishing

All column names:
qty_dot_url
qty_hyphen_url
qty_underline_url
qty_slash_url
qty_questionmark_url
qty_equal_url
qty_at_url
qty_and_url
qty_exclamation_url
qty_space_url
qty_tilde_url
qty_comma_url
qty_plus_url
qty_asterisk_url
qty_hashtag_url
qty_dollar_url
qty_percent_url
qty_tld_url
length_url
qty_dot_domain
qty_hyphen_domain
qty_underline_domain
qty_slash_domain
qty_questionmark_domain
qty_equal_domain
qty_at_domain
qty_and_domain
qty_exclamation_domain
qty_space_domain
qty_tilde_domain
qty_comma_domain
qty_plus_domain
qty_asterisk_domain
qty_hashtag_domain
qty_dollar_domain
qty_percent_domain
qty_vowels_domain
domain_length
domain_in_ip
server_client_domain
qty_dot_directory
qty_hyphen_directory
qty_underline_directory
qty_slash_directory
qty_questionmark_directory
qty_equal_directory
qty_at_directory
qty_and_directory
qty_exclamation_directory
qty_space_directory
qty_tilde_directory
qty_comma_directory
qty_plus_directory
qty_asterisk_directory
qty_hashtag_directory
qty_dollar_directory
qty_percent_directory
directory_length
qty_dot_file
qty_hyphen_file
qty_underline_file
qty_slash_file
qty_questionmark_file
qty_equal_file
qty_at_file
qty_and_file
qty_exclamation_file
qty_space_file
qty_tilde_file
qty_comma_file
qty_plus_file
qty_asterisk_file
qty_hashtag_file
qty_dollar_file
qty_percent_file
file_length
qty_dot_params
qty_hyphen_params
qty_underline_params
qty_slash_params
qty_questionmark_params
qty_equal_params
qty_at_params
qty_and_params
qty_exclamation_params
qty_space_params
qty_tilde_params
qty_comma_params
qty_plus_params
qty_asterisk_params
qty_hashtag_params
qty_dollar_params
qty_percent_params
params_length
tld_present_params
qty_params
email_in_url
time_response
domain_spf
asn_ip
time_domain_activation
time_domain_expiration
qty_ip_resolved
qty_nameservers
qty_mx_servers
ttl_hostname
tls_ssl_certificate
qty_redirects
url_google_index
domain_google_index
url_shortened
phishing

Target values:
[np.int64(0), np.int64(1)]

In [33]:
from pathlib import Path

data_folder = Path(
    r"C:\Users\asand\OneDrive\Documents\GitHub\machine-learning-phishing-url-detection\data"
)

for file in data_folder.iterdir():
    print(file.name)

dataset_full.csv

In [34]:
from pathlib import Path

data_folder = Path(
    r"C:\Users\asand\OneDrive\Documents\GitHub"
    r"\machine-learning-phishing-url-detection\data"
)

print("Data folder exists:", data_folder.exists())

if data_folder.exists():
    for file in data_folder.iterdir():
        print(file.name)

Data folder exists: True
dataset_full.csv